ScrollingView:

<ScrollingView@ScrollView>
    BoxLayout:
        orientation: "vertical"
        FirstPageView:
        SecondWidget:

# SecondWidget:

<SecondWidget@AnchorLayout>:
    anchor_x: "center"
    anchor_y: "bottom"
    BoxLayout:
        orientation: "vertical"
        size_hint: .2, .2
        Button:
            text: "Do it"
            size: "100dp", "50dp"
            background_color: .2, 1, .1, 1
            # pos: "200dp", 0